// src/components/SidebarNav.jsx
import React from 'react';
import {
  FaBasketballBall, FaChartBar, FaUsers, FaTasks, FaCog,
  FaRegClipboard, FaLightbulb, FaBookOpen, FaToolbox, FaChartPie, FaUserCircle, FaDumbbell, FaSitemap, FaCheckCircle, 
  FaClipboardList, FaRegClock, FaHeartbeat, FaBolt, FaCalendarAlt, FaAward, FaUserAlt, FaSmile, FaChartLine, FaUserShield,
    FaMoneyBillWave, FaClipboardCheck, FaUsersCog, FaUserFriends, FaChalkboardTeacher, FaMoneyBillAlt, FaUserTie, FaCogs,
    FaRobot, FaCommentDots, FaBrain, FaBook, FaArrowCircleUp, FaExclamationTriangle, FaRunning, FaRoad, FaHandHoldingHeart,
    FaGavel, FaRocket, FaCrown, FaHistory, FaBullseye, FaProjectDiagram, FaFileExport, FaGlobeEurope, FaSync, FaUserGraduate,
    FaCloudDownloadAlt, FaBalanceScale, FaRegListAlt, FaBullhorn, FaPlus, FaGlobe, 
    FaMapMarkedAlt, FaTable, FaAccessibleIcon, FaShieldAlt, FaPlaneDeparture, FaCubes, FaHandshake,
     FaRegStar, FaFileContract, FaExchangeAlt, FaChartArea, FaLock, FaArrowUp, FaRulerVertical, FaFlagUsa, FaLayerGroup } from 'react-icons/fa';

const navItems = [
  { key: 'BoardroomCockpit', label: 'Boardroom Cockpit', icon: <FaBullseye /> },
  { key: 'BoardroomDnDPipeline', label: 'Action Pipeline', icon: <FaClipboardCheck /> },
  { key: 'ControlTower', label: 'CONTROL TOWER', icon: <FaBullseye /> },
  { key: 'Athletes', label: 'Athlete Pathway', icon: <FaBasketballBall /> },
  { key: 'TrainingWindow', label: 'Training Window Optimizer', icon: <FaBolt /> },
  { key: 'Coaches', label: 'Coach Pathway', icon: <FaUsers /> },
  { key: 'CoachReflection', label: 'Coach Reflection Diary', icon: <FaBook /> },
  { key: 'Club', label: 'Club Dashboard', icon: <FaChartBar /> },
  { key: 'Analytics', label: 'Performance Analytics', icon: <FaChartPie /> },
  { key: 'Toolkit', label: 'Strategic Toolkit', icon: <FaToolbox /> },
  { key: 'Diagnostic', label: 'Diagnostic Toolkit', icon: <FaRegClipboard /> },
  { key: 'Scenario', label: 'Scenario Builder', icon: <FaLightbulb /> },
  { key: 'Benchmarking', label: 'Benchmarking', icon: <FaBookOpen /> },
  { key: 'AdvancedAnalytics', label: 'Advanced Analytics', icon: <FaChartBar /> },
  { key: 'MarketIntelligence', label: 'Market Intelligence', icon: <FaCog /> },
  { key: 'ExecutiveSummary', label: 'Board Mode', icon: <FaTasks /> },
  { key: 'EvaluationChecklist', label: 'Evaluation/Checklist', icon: <FaRegClipboard /> },
  { key: 'TaskTracker', label: 'Task Board', icon: <FaTasks /> },
  { key: 'PathwayBuilder', label: 'Pathway Builder', icon: <FaLightbulb /> },
  { key: 'ProfileProgress', label: 'Profile Progress', icon: <FaUserCircle /> },
  { key: 'ResourcePlanningDashboard', label: 'Resource Planning', icon: <FaDumbbell /> },
  { key: 'OrgChartVisualizer', label: 'Org Chart', icon: <FaSitemap /> },
  { key: 'GovernanceSelfAudit', label: 'Gov. Self-Audit', icon: <FaCheckCircle /> },
  { key: 'BoardroomDecisionLog', label: 'Board Decisions', icon: <FaCheckCircle /> },
  { key: 'BoardPackGenerator', label: 'Board Pack', icon: <FaClipboardList /> },
  { key: 'BoardKPIDashboard', label: 'Board KPIs', icon: <FaChartBar /> },
  { key: 'ComplianceCalendar', label: 'Compliance', icon: <FaRegClock /> },
  { key: 'PlayerHolisticDashboard', label: 'Player 360', icon: <FaHeartbeat /> },
  { key: 'PlayerHolisticSuperDashboard', label: 'Player 360+', icon: <FaHeartbeat /> },
  { key: 'SensitivePeriodsTracker', label: 'Sensitive Periods', icon: <FaBolt /> },
  { key: 'PracticeGameRatioAnalyzer', label: 'Practice/Game Ratio', icon: <FaChartBar /> },
  { key: 'PeriodizationPlanner', label: 'Periodization Planner', icon: <FaCalendarAlt /> },
  { key: 'SessionPlanBuilder', label: 'Session Plan', icon: <FaClipboardList /> },
  { key: 'SkillsPassport', label: 'Skills Passport', icon: <FaAward /> },
  { key: 'AthleteWellnessDashboard', label: 'Athlete Wellness', icon: <FaHeartbeat /> },
  { key: 'clubHealth', label: 'Club Health', icon: <FaHeartbeat /> },
  { key: "resourcePortal", label: "Resource Portal", icon: <FaBookOpen /> },
  { key: "parentPortal", label: "Parent Portal", icon: <FaUserAlt /> },
  { key: "athleteFeedback", label: "Athlete Feedback", icon: <FaSmile /> },
  { key: "aiProjections", label: "AI Projections", icon: <FaChartLine /> },
  { key: "individualPlan", label: "Individual Plan", icon: <FaClipboardList /> },
  { key: "SelfAssessment", label: "Self-Assessment", icon: <FaClipboardList /> },
  { key: "EthicsCharacter", label: "Ethics/Character", icon: <FaUserShield /> },
  { key: "FinancialEquity", label: "Financial Equity", icon: <FaMoneyBillWave /> },
  { key: "GrantAnalyzer", label: "Grant Analyzer", icon: <FaClipboardCheck /> },
  { key: "BoardHealth", label: "Board Health", icon: <FaUsersCog /> },
  { key: "ParentPulse", label: "Parent Pulse", icon: <FaUserFriends /> },
  { key: "CoachMatrix", label: "Coach Matrix", icon: <FaChalkboardTeacher /> },
  { key: "SuccessionMatrix", label: "Succession Matrix", icon: <FaClipboardList /> },
  { key: "TalentPipeline", label: "Talent Pipeline", icon: <FaChartLine /> },
  { key: "PlayerContracts", label: "Player Contracts", icon: <FaMoneyBillAlt /> },
  { key: "agentTracker", label: "Agent Tracker", icon: <FaUserTie /> },
  { key: 'HighPerformance', label: 'High-Performance', icon: <FaChartLine /> },
  { key: "KPIMatrix", label: "KPI Matrix", icon: <FaChartBar /> },
  { key: "Benchmarking", label: "Benchmarking", icon: <FaChartPie /> },
  { key: "ResourceGap", label: "Resource Gap", icon: <FaCogs /> },
  { key: "ReadinessMatrix", label: "Readiness Matrix", icon: <FaClipboardCheck /> },
  { key: "StakeholderMap", label: "Stakeholder Map", icon: <FaUsers /> },
  { key: "GameDesigner", label: "Game Designer", icon: <FaClipboardList /> },
  { key: "BoardCockpit", label: "Board Cockpit", icon: <FaUserTie /> },
  { key: 'AthletePathwayEngine', label: 'Athlete Pathway Engine', icon: <FaChartLine /> },
  { key: 'AthleteDashboard', label: 'Athlete Dashboard', icon: <FaChartLine /> },
  { key: 'CoachImpactAnalyzer', label: 'Coach Impact Analyzer', icon: <FaUserTie /> },
  { key: 'PlayerTransitionScenarioBuilder', label: 'Transition Scenario', icon: <FaChartLine /> },
  { key: 'PlayerTransitionComparison', label: 'Transition Comparison', icon: <FaChartLine /> },
  { key: 'PlayerScenarioAI', label: 'Scenario AI Lab', icon: <FaRobot /> },
  { key: 'OrgScenarioAICockpit', label: 'Org AI Cockpit', icon: <FaRobot /> },
  { key: 'BoardroomTools', label: 'Boardroom Tools', icon: <FaCogs /> },
  { key: 'BoardroomChat', label: 'Boardroom Chat', icon: <FaCommentDots /> },
  { key: "LTADCompliance", label: "LTAD Compliance", icon: <FaClipboardCheck /> },
  { key: "TransitionHeatmap", label: "Transition Risk", icon: <FaBolt /> },
  { key: "StakeholderScorecard", label: "Stakeholder Scorecard", icon: <FaUsers /> },
  { key: "MarketGapRadar", label: "Market Radar", icon: <FaChartPie /> },
  { key: "DynamicRoleRoadmap", label: "Role Roadmap", icon: <FaUserTie /> },
  { key: 'EnrichedMarketReport', label: 'Enriched Market Report', icon: <FaBookOpen /> },
  { key: 'AthleteDevelopmentPathway', label: 'Athlete Pathway Module', icon: <FaChartLine /> },
  { key: 'AthleteWellnessVoice', label: 'Wellness & Player Voice', icon: <FaBrain /> },
  { key: 'SponsorshipScanner', label: 'Sponsorship Scanner', icon: <FaMoneyBillWave /> },
  { key: 'DynamicRolePromotion', label: 'Role Promotion Predictor', icon: <FaArrowCircleUp /> },
  { key: 'RiskDashboard', label: 'Risk Dashboard', icon: <FaExclamationTriangle /> },
  { key: 'PeerComparison', label: 'Peer Club Comparison', icon: <FaChartPie /> },
  { key: 'MicrocycleDesigner', label: 'Microcycle Designer', icon: <FaCalendarAlt /> },
  { key: 'SessionLibrary', label: 'Session Library', icon: <FaBookOpen /> },
  { key: 'PathwayTransparency', label: 'Pathway Transparency', icon: <FaRoad /> },
  { key: 'InsightToActionLog', label: 'Insight-to-Action Log', icon: <FaClipboardCheck /> },
  { key: 'StakeholderEngagement', label: 'Stakeholder Engagement', icon: <FaUsers /> },
  { key: 'FacilityAudit', label: 'Facility Audit', icon: <FaSitemap /> },
  { key: 'VolunteerPipeline', label: 'Volunteer Pipeline', icon: <FaUsers /> },
  { key: 'CommunityImpact', label: 'Community Impact', icon: <FaHandHoldingHeart /> },
  { key: 'DecisionInsightActionLog', label: 'Insight–Action Log', icon: <FaClipboardList /> },
  { key: 'AINextBestAction', label: 'AI Actions', icon: <FaRobot /> },
  { key: 'PolicyComplianceMasterLog', label: 'Policy & Compliance', icon: <FaGavel /> },
  { key: 'CoachCPDTracker', label: 'Coach CPD Tracker', icon: <FaChalkboardTeacher /> },
  { key: 'ClubBoardroomDiagnostic', label: 'Board Diagnostic', icon: <FaClipboardCheck /> },
  { key: 'InnovationBoard', label: 'Innovation Board', icon: <FaLightbulb /> },
  { key: 'DataPrivacyEthics', label: 'Data Privacy & Ethics', icon: <FaUserShield /> },
  { key: 'AcceleratorRoadmap', label: '90-Day Accelerator', icon: <FaRocket /> },
  { key: "GlobalAuditLog", label: "Audit & Activity Log", icon: <FaHistory /> },
  { key: "BoardDecisionCalendar", label: "Decision Calendar", icon: <FaCalendarAlt /> },
  { key: "AINextBestAction", label: "AI Concierge", icon: <FaRobot /> },
  { key: 'RoleClarity', label: 'Role Clarity Matrix', icon: <FaSitemap /> },
  { key: 'DevStages', label: 'Development Stages', icon: <FaChartLine /> },
  { key: 'FinancialOptimizer', label: 'Finance Optimizer', icon: <FaMoneyBillWave /> },
  { key: 'OpsBlueprint', label: 'Ops Efficiency', icon: <FaToolbox /> },
  { key: 'GovCompliance', label: 'Governance & Compliance', icon: <FaCheckCircle /> },
  { key: 'BoardSentiment', label: 'Board Sentiment', icon: <FaChartBar /> },
  { key: 'RoleConflictRadar', label: 'Role Conflict Radar', icon: <FaSitemap /> },
  { key: 'ScenarioSimulator', label: 'Scenario Simulator', icon: <FaChartPie /> },
  { key: 'PrivacyEthicsCompliance', label: 'Privacy & Ethics Compliance', icon: <FaUserShield /> },
  { key: 'StrategicAlignmentDashboard', label: 'Strategic Alignment', icon: <FaBullseye /> },
  { key: 'YouthParticipationProjection', label: 'Youth Projection Engine', icon: <FaChartLine /> },
  { key: 'ResourceDashboard', label: 'Resource Dashboard', icon: <FaDumbbell /> },
  { key: 'ConsistencyDashboard', label: 'Consistency Dashboard', icon: <FaChartLine /> },
  { key: 'ClubManagementOptimizationDashboard', label: 'Club Management Optimization', icon: <FaClipboardList /> },
  { key: 'OrganizationalIntegrationChart', label: 'Org Integration Chart', icon: <FaCogs /> },
  { key: 'StrategicExecutionDashboard', label: 'Strategic Execution', icon: <FaChartBar /> },
  { key: 'ImplementationMonitoringDashboard', label: 'Implementation & Monitoring', icon: <FaCheckCircle /> },
  { key: 'ComplianceMonitoringDashboard', label: 'Compliance & Monitoring', icon: <FaUserShield /> },
  { key: 'StrategicGrowthDashboard', label: 'Strategic Growth', icon: <FaRocket /> },
  { key: 'StrategicExecutionPlanDashboard', label: 'Strategic Execution Plan', icon: <FaChartBar /> },
  { key: 'SystemAlignmentMap', label: 'System Alignment Map', icon: <FaProjectDiagram /> },
  { key: 'CompetencyFrameworkDashboard', label: 'Competency Framework', icon: <FaClipboardList /> },
  { key: 'MeetingAgendaDashboard', label: 'Meeting Agenda', icon: <FaClipboardList /> },
  { key: "ClubOperationalEfficiencyModel", label: "Operational Efficiency", icon: <FaCog /> },
  { key: 'WhatIfSimulator', label: 'WHAT-IF SIM', icon: <FaRobot /> },
  { key: 'ComplianceAutomation', label: 'Compliance Center', icon: <FaClipboardCheck /> },
  { key: 'AINextActionEngine', label: 'AI Action Engine', icon: <FaRobot /> },
  { key: 'AuditTrail', label: 'Audit Trail', icon: <FaHistory /> },
  { key: 'ReportGenerator', label: 'BOARD PACK / REPORT', icon: <FaFileExport /> },
  { key: 'CoachProfile', label: 'Coach 360', icon: <FaUserTie /> },
  { key: 'LanguageSettings', label: 'Language', icon: <FaGlobeEurope /> },
  { key: 'DemoMode', label: 'Demo Data/Reset', icon: <FaSync /> },
  { key: 'SponsorshipActivationDashboard', label: 'Sponsorship Activation Dash', icon: <FaMoneyBillWave /> },
  { key: 'PerformanceReviewCycle', label: 'Performance Review Cycle', icon: <FaClipboardCheck /> },
  { key: 'SponsorshipActivationBoard', label: 'Sponsorship Activation', icon: <FaBullseye /> },
  { key: 'SponsorshipValueProjection', label: 'Sponsorship Value Projection', icon: <FaMoneyBillWave /> },
  { key: 'PeriodizationCockpit', label: 'Periodization Cockpit', icon: <FaBasketballBall /> },
  { key: 'SponsorshipValueAnalytics', label: 'Sponsorship Value Analytics', icon: <FaChartLine /> },
  { key: 'RiskContingencyDashboard', label: 'Risk & Contingency', icon: <FaExclamationTriangle /> },
  { key: 'AthleteCompetitionPathwayDashboard', label: 'Athlete Pathway', icon: <FaRunning /> },
  { key: 'ClubStrategicGrowth', label: 'CLUB GROWTH', icon: <FaChartBar /> },
  { key: 'TalentPipelineLiveMap', label: 'TALENT LIVE MAP', icon: <FaUserGraduate /> },
  { key: 'BoardroomDisputeCockpit', label: 'DISPUTE & COMPLIANCE', icon: <FaGavel /> },
  { key: 'DTC', label: 'Digital Transformation Center', icon: <FaCogs /> },
  { key: 'GIH', label: 'Global Intelligence Hub', icon: <FaGlobeEurope /> },
  { key: 'BTV', label: 'Blockchain Talent Verification', icon: <FaRocket /> },
  { key: 'DigitalPerformanceLab', label: 'Performance Lab', icon: <FaCloudDownloadAlt /> },
  { key: 'LongTermDevelopmentPlan', label: 'Long-Term Dev. Plan', icon: <FaChartLine /> },
  { key: 'OperationalHealthDiagnostic', label: 'Operational Health', icon: <FaHeartbeat /> },
  { key: 'ProgressSnapshotCockpit', label: 'Progress Cockpit', icon: <FaChartLine /> },
  { key: 'OrgEcosystemMap', label: 'Org Ecosystem', icon: <FaUserTie /> },
  { key: 'QuarterlyProgressReport', label: 'Quarterly Report', icon: <FaChartLine /> },
  { key: 'AthleteProgressDashboard', label: 'Athlete Progress', icon: <FaUserTie /> },
  { key: 'MultiAthleteProgressDashboard', label: 'Athlete Boardroom', icon: <FaUserTie /> },
  { key: 'DecisionLogElite', label: 'Decision Log Elite', icon: <FaCrown /> },
  { key: 'BoardroomPackSuite', label: 'Boardroom Pack', icon: <FaClipboardList /> },
  { key: 'TalentVulnerabilityTracker', label: 'Talent Vulnerability', icon: <FaHeartbeat /> },
  { key: 'OrgDiagnosticScoringSuite', label: 'Org Scoring', icon: <FaBalanceScale /> },
  { key: 'FeedbackLoopSuite', label: 'Feedback Loop', icon: <FaChartLine /> },
  { key: 'AssessmentTemplateSuite', label: 'Assessments', icon: <FaClipboardList /> },
  { key: 'OperationalRoleClarityCockpit', label: 'Role Clarity', icon: <FaUserTie /> },
  { key: 'TalentAlumniIntelligenceSuite', label: 'Talent & Alumni', icon: <FaUserTie /> },
  { key: 'FinancialScenarioSuite', label: 'Finance Scenarios', icon: <FaMoneyBillWave /> },
  { key: 'ProTeamOpsWarRoom', label: 'Team Ops War Room', icon: <FaCalendarAlt /> },
  { key: 'OperationalRACIScoredMatrix', label: 'RACI Matrix', icon: <FaUserTie /> },
  { key: 'BoardroomIntelligenceFusionCenter', label: 'Boardroom Cockpit', icon: <FaSitemap /> },
  { key: 'AthleteProgress360', label: 'Athlete Progress 360', icon: <FaCheckCircle /> },
  { key: 'InjuryRecoveryCockpit', label: 'Injury Recovery', icon: <FaHeartbeat /> },
  { key: 'PlayerScoutingMatrix', label: 'Scouting Matrix', icon: <FaRegListAlt /> },
  { key: 'StrategicGrowthExpansionEngine', label: 'Strategic Growth', icon: <FaRocket /> },
  { key: 'StaffVolunteerHRDevelopmentSuite', label: 'Staff & HR Suite', icon: <FaUserTie /> },
  { key: 'CommunicationAnnouncementMatrix', label: 'Comms Matrix', icon: <FaBullhorn /> },
  { key: 'CommunityEngagementSocialImpactDashboard', label: 'Community Impact', icon: <FaHandHoldingHeart /> },
  { key: 'AthleteProgressIDCardSuite', label: 'Athlete ID Cards', icon: <FaUserTie /> },
  { key: 'InjuryRecoveryRTP', label: 'Injury Recovery', icon: <FaHeartbeat /> },
  { key: 'TrainingMicrocycleBuilder', label: 'Training Microcycle', icon: <FaClipboardList /> },
  { key: 'PlayerScoutingTracker', label: 'Player Scouting', icon: <FaClipboardList /> },
  { key: 'StaffHRDevelopmentSuite', label: 'Staff & HR Suite', icon: <FaUserTie /> },
  { key: 'CommsBoardroomCockpit', label: 'Comms Boardroom', icon: <FaBullhorn /> },
  { key: 'CommunityImpactStudio', label: 'Community Impact', icon: <FaGlobe /> }, 
  { key: 'StakeholderPipelineSuite', label: 'Stakeholder Pipeline', icon: <FaUsers /> },
  { key: 'ProgressReportingCenter', label: 'Progress Reports', icon: <FaCalendarAlt /> },
  { key: 'GameBasedSessionPlanner', label: 'Session Planner', icon: <FaBasketballBall /> },
  { key: 'LTADComplianceCockpit', label: 'LTAD Compliance', icon: <FaClipboardCheck /> },  
  { key: 'BrandAssetPortfolioCockpit', label: 'Brand & Assets', icon: <FaClipboardList /> },
  { key: 'EquityHeatmap', label: 'Equity & Access Heatmap', icon: <FaMapMarkedAlt /> },
  { key: 'PhysicalLiteracy', label: 'Physical Literacy Engine', icon: <FaRunning /> },
  { key: 'PolicyFunding', label: 'Policy & Funding Radar', icon: <FaBalanceScale /> },
  { key: 'BarrierSuite', label: 'Barrier Solution Suite', icon: <FaChartBar /> },
  { key: 'FamilyPulse', label: 'Family Engagement Pulse', icon: <FaUsers /> },
  { key: 'AdaptiveDesigner', label: 'Adaptive Sports Designer', icon: <FaAccessibleIcon /> },
  { key: 'SafeSport', label: 'SafeSport Compliance', icon: <FaShieldAlt /> },
  { key: 'RetentionRadar', label: 'Retention Risk Radar', icon: <FaBullseye /> },
  { key: 'TalentResilience', label: 'Resilience Builder', icon: <FaShieldAlt /> },
  { key: 'EliteTransition', label: 'Transition Cockpit', icon: <FaPlaneDeparture /> },
  { key: 'ParentMatrix', label: 'Parent Matrix', icon: <FaUsers /> },
  { key: 'GameEnvOpt', label: 'Game Optimizer', icon: <FaCalendarAlt /> },
  { key: 'PowerMap', label: 'Power Map', icon: <FaSitemap /> },
  { key: 'AgeBiasAnalyzer', label: 'Age Bias Impact', icon: <FaBalanceScale /> },
  { key: 'SkillMasterMap', label: 'Skill Progression', icon: <FaCubes /> },
  { key: 'GameSessionDesigner', label: 'Session Designer', icon: <FaBasketballBall /> },
  { key: 'DecisionImpactVault', label: 'Decision Vault', icon: <FaGavel /> },
  { key: 'RoleEvolutionMatrix', label: 'Role Evolution', icon: <FaUserTie /> },
  { key: 'StakeholderMatrix', label: 'Stakeholder Matrix', icon: <FaUsers /> },
  { key: 'ResilienceCockpit', label: 'Resilience Cockpit', icon: <FaShieldAlt /> },
  { key: 'DecisionMastery', label: 'Decision Mastery', icon: <FaSitemap /> },
  { key: 'SponsorshipEngine', label: 'Sponsorship Engine', icon: <FaHandshake /> },
  { key: 'PlayerOpportunityRadar', label: 'Player Opportunity Radar', icon: <FaRegStar /> },
  { key: 'SquadMatrix', label: 'Squad Matrix', icon: <FaCalendarAlt /> },
  { key: 'ContractLifecycle', label: 'Contract Analyzer', icon: <FaFileContract /> },
  { key: 'MobilityScenario', label: 'Mobility Simulator', icon: <FaExchangeAlt /> },
  { key: 'TrialList', label: 'Trial List', icon: <FaClipboardList /> },
  { key: 'VolatilityAnalyzer', label: 'Volatility Analyzer', icon: <FaChartArea /> },
  { key: 'GrowthWindow', label: 'Growth Windows', icon: <FaChartLine /> },
  { key: 'EnvAudit', label: 'Env Audit', icon: <FaExclamationTriangle /> },
  { key: 'TalentEquityVisualizer', label: 'Talent Equity Visualizer', icon: <FaBalanceScale /> },
  { key: 'StrategicAlignmentBoard', label: 'Strategic Alignment Board', icon: <FaProjectDiagram /> },
  { key: 'CoachDevMatrix', label: 'Coach Dev Matrix', icon: <FaUserTie /> },
  { key: 'ResourceUtilDashboard', label: 'Resource Utilization', icon: <FaCogs /> },
  { key: 'ParticipationDropoutAnalyzer', label: 'Participation & Dropout', icon: <FaChartPie /> },
  { key: 'StakeholderEngagementCockpit', label: 'Stakeholder Engagement', icon: <FaUsers /> },
  { key: 'TalentPipelineVulnerabilityRadar', label: 'Talent Pipeline Radar', icon: <FaShieldAlt /> },
  { key: 'AthleteMilestoneTimeline', label: 'Milestone Timeline', icon: <FaRunning /> },
  { key: 'AthleteTimelineCompareGantt', label: 'Compare Gantt', icon: <FaChartBar /> },
  { key: 'LimitBreakerCard', label: 'Limit Breaker Card', icon: <FaLightbulb /> },
  { key: 'ProTransitionReadinessDashboard', label: 'Pro Transition Dashboard', icon: <FaClipboardCheck /> },
  { key: 'SquadVulnerabilityRadarElite', label: 'Squad Builder & Radar', icon: <FaBasketballBall /> },
  { key: 'OrgResilienceDisruptionDashboard', label: 'Org Resilience', icon: <FaShieldAlt /> },
  { key: 'FinancialScenarioSponsorshipSimulator', label: 'Finance & Sponsorship', icon: <FaMoneyBillWave /> },
  { key: 'ClubDNAAlignmentElite', label: 'DNA Alignment Audit', icon: <FaBullseye /> },
  { key: 'StrategicRoadmapCockpitElite', label: 'Strategic Roadmap', icon: <FaProjectDiagram /> },
  { key: 'StakeholderMapInfluenceElite', label: 'Stakeholder Map', icon: <FaUsers /> },
  { key: 'TalentRiskSuccessionMatrixElite', label: 'Talent Succession Matrix', icon: <FaTable /> },
  { key: 'PolicyChangeRadarElite', label: 'Policy Radar', icon: <FaBalanceScale /> },
  { key: 'StrategicInfluenceImpactMapElite', label: 'Influence Map', icon: <FaProjectDiagram /> },
  { key: 'BoardroomAISensemakingArena', label: 'AI Boardroom Arena', icon: <FaCrown /> },
  { key: 'AthleteExperienceEngagementSuite', label: 'Athlete Engagement', icon: <FaHeartbeat /> },
  { key: 'BrandEquityCommandCenter', label: 'Brand Command', icon: <FaRocket /> },
  { key: 'InnovationBestPracticeBoard', label: 'Innovation Board', icon: <FaRocket /> },
  { key: 'DigitalAssetIPManagementSuite', label: 'IP & Asset Vault', icon: <FaLock /> },
  { key: 'ProgressionEngineElite', label: 'Progression Engine', icon: <FaArrowUp /> },
  { key: 'BoardroomDecisionLogAI', label: 'Board Decisions & AI', icon: <FaClipboardList /> },

  { key: 'PHVModule', label: 'PHV Growth Tracker', icon: <FaRulerVertical /> },
{ key: 'LTADComplianceDashboard', label: 'LTAD Compliance', icon: <FaClipboardCheck /> },
{ key: 'SensitivePeriodsEngine', label: 'Sensitive Periods AI', icon: <FaBolt /> },
{ key: 'RatioAnalyzer', label: 'Practice/Game Ratio', icon: <FaBalanceScale /> },
{ key: 'HolisticPlayerDashboard', label: 'Holistic Dashboard', icon: <FaCheckCircle /> },
{ key: 'CoachDevelopmentIntegration', label: 'Coach Dev. Integration', icon: <FaUserTie /> },
{ key: 'ParentEngagementSuite', label: 'Parent Engagement', icon: <FaUsers /> },
{ key: 'RetentionDropoutHeatmap', label: 'Dropout Heatmap', icon: <FaExclamationTriangle /> },
{ key: 'TransitionRetentionEngine', label: 'Transition Engine', icon: <FaUserGraduate /> },
{ key: 'CognitiveSkillsMatrix', label: 'Cognitive Matrix', icon: <FaBrain /> },
{ key: 'SocioEmotionalResilience', label: 'Socio-Emotional Resilience', icon: <FaHeartbeat /> },
{ key: 'MultiContextReadiness', label: 'Competition Readiness Engine', icon: <FaBolt /> },
{ key: 'CoachAthleteFitMatrix', label: 'Coach–Athlete Fit Matrix', icon: <FaHandshake /> },
{ key: 'AcademicDualPathwayProgress', label: 'Academic/Dual-Pathway', icon: <FaUserGraduate /> },
{ key: 'LongTermAthleteProjectionSim', label: 'LT Athlete Projection', icon: <FaChartLine /> },
{ key: 'CommunityFamilyEngagementLab', label: 'Engagement Impact Lab', icon: <FaHandHoldingHeart /> },
{ key: 'RecoveryInjuryPreventionSuite', label: 'Recovery & Injury Suite', icon: <FaHeartbeat /> },
{ key: 'TransitionPathwaysBoard', label: 'Transition Pathways Board', icon: <FaFlagUsa /> },
{ key: 'InvisibleAthleteDetector', label: 'Invisible Athlete Detector', icon: <FaUserAlt /> },
{ key: 'CognitiveInjuryRecoveryDashboard', label: 'Injury Recovery Casefiles', icon: <FaBrain /> },
{ key: 'RoleEvolutionPromotionSimulator', label: 'Role Evolution Simulator', icon: <FaLayerGroup /> },
{ key: 'RoleIdentityClarityEngine', label: 'Role DNA & Clarity Engine', icon: <FaLayerGroup /> },
{ key: 'EnvironmentalAdaptabilityLab', label: 'Adaptability Stress Lab', icon: <FaBolt /> },
{ key: 'MentalLoadOptimizationSuite', label: 'Mental Load Suite', icon: <FaBrain /> },
{ key: 'SocialCohesionAnalyticsStudio', label: 'Cohesion Studio', icon: <FaUsers /> },
{ key: 'LearningAgilityMatrix', label: 'Learning Agility Matrix', icon: <FaUserGraduate /> },
{ key: 'RelativeAgeEffectAnalyzer', label: 'RAE & Equity Analyzer', icon: <FaBalanceScale /> },
{ key: 'GameSenseCoachLab', label: 'Game Sense Coach Lab', icon: <FaLightbulb /> },
{ key: 'PositionalProficiencyTracker', label: 'Positional Tracker', icon: <FaUserTie /> },
{ key: 'DefensiveFootworkSimulator', label: 'Defense Simulator', icon: <FaShieldAlt /> },
{ key: 'TeamCohesionAnalyticsStudio', label: 'Cohesion Studio', icon: <FaUsers /> },
{ key: 'StrategicOpsFusionCockpit', label: 'Strategic Ops Fusion', icon: <FaRocket /> },
{ key: 'PracticeOptimizerLab', label: 'Practice Optimizer', icon: <FaDumbbell /> },
{ key: 'OrganizationalCultureEngine', label: 'Culture & Leadership', icon: <FaHandHoldingHeart /> },
];

const SidebarNav = ({ setView, currentView, boardroomMode, setBoardroomMode }) => (
  <nav style={{
    width: 250,
    minHeight: '100vh',
    background: 'rgba(24,36,51,0.99)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    borderRight: '2px solid #283E51',
    padding: '28px 0',
    position: 'sticky',
    top: 0,
    zIndex: 20,
    boxShadow: '6px 0 18px #181e2335'
  }}>
    <div style={{ textAlign: 'center', marginBottom: 34 }}>
      <img src="/logo.png" alt="CourtEvo Vero" style={{
        width: 64,
        marginBottom: 8,
        borderRadius: 14,
        boxShadow: '0 2px 10px #FFD70055'
      }} />
      <div style={{
        color: '#FFD700',
        fontWeight: 900,
        fontSize: 22,
        letterSpacing: 1,
        marginTop: 0,
        textShadow: '0 2px 20px #FFD70088'
      }}>
        COURTEVO VERO
      </div>
    </div>
    <div style={{ flex: 1 }}>
      {navItems.map(item => (
        <button
          key={item.key}
          onClick={() => setView(item.key)}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 18,
            width: '100%',
            background: currentView === item.key ? '#FFD700' : 'transparent',
            color: currentView === item.key ? '#222' : '#fff',
            border: 'none',
            outline: 'none',
            fontWeight: 700,
            fontSize: 17,
            padding: '13px 32px',
            cursor: 'pointer',
            transition: 'background 0.13s, color 0.13s, box-shadow 0.18s',
            borderLeft: currentView === item.key ? '7px solid #FFD700' : '7px solid transparent',
            borderRadius: currentView === item.key ? '0 20px 20px 0' : 0,
            marginBottom: 2,
            boxShadow: currentView === item.key ? '0 2px 18px #FFD70033' : 'none'
          }}
        >
          <span style={{ fontSize: 20 }}>{item.icon}</span>
          {item.label}
        </button>
      ))}
    </div>
    <div style={{margin: '25px 0 0 0', textAlign: 'center'}}>
      <button
        onClick={() => setBoardroomMode(b => !b)}
        style={{
          background: boardroomMode ? '#FFD700' : '#1de682',
          color: '#23292f',
          fontWeight: 900,
          fontSize: 16,
          borderRadius: 16,
          padding: '10px 20px',
          boxShadow: '0 3px 16px #1de68255',
          border: 'none',
          cursor: 'pointer',
          transition: 'all 0.18s',
          marginTop: 10
        }}>
        <FaRobot style={{ marginRight: 8, fontSize: 18 }} />
        {boardroomMode ? 'Back to App' : 'Boardroom Mode'}
      </button>
    </div>
  </nav>
);

export default SidebarNav;
